version: '3.8'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-app
    ports:
      - "80:80" # Sirve en el puerto 8080
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
